//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Searcher.CL.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Searcher.CL.Tests.TestData", typeof(TestData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///	&lt;body&gt;
        ///		&lt;p class=&quot;row&quot; data-pid=&quot;4411995504&quot;&gt; &lt;a href=&quot;http://ocala.craigslist.org/sof/4411995504.html&quot; class=&quot;i&quot;&gt;&lt;/a&gt; &lt;span class=&quot;star v&quot; title=&quot;save this post in your favorites list&quot;&gt;&lt;/span&gt; &lt;span class=&quot;pl&quot;&gt; &lt;span class=&quot;date&quot;&gt;Apr  7&lt;/span&gt;  &lt;a href=&quot;http://ocala.craigslist.org/sof/4411995504.html&quot;&gt; ASP.net C# MVC Web Developer Padawan&lt;/a&gt; &lt;/span&gt; &lt;span class=&quot;l2&quot;&gt;   &lt;span class=&quot;pnr&quot;&gt; &lt;small&gt; (Ocala, FL)&lt;/small&gt; &lt;span class=&quot;px&quot;&gt; &lt;span class=&quot;p&quot;&gt; &lt;span class=&quot;maptag&quot; data-pid=&quot;4411995504&quot;&gt;ma [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JobPostingRow {
            get {
                return ResourceManager.GetString("JobPostingRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html class=&quot;nojs&quot;&gt;&lt;head&gt;
        ///    &lt;title&gt;orlando software/QA/DBA/etc jobs classifieds &amp;quot; C#&amp;quot; - craigslist&lt;/title&gt;
        ///
        ///    &lt;meta name=&quot;description&quot; content=&quot;orlando software/QA/DBA/etc jobs classifieds &amp;quot; C#&amp;quot; - craigslist&quot;&gt;
        ///    &lt;link rel=&quot;alternate&quot; type=&quot;application/rss+xml&quot; href=&quot;http://orlando.craigslist.org/search/sof?query=%20C%23&amp;amp;s=0&amp;amp;format=rss&quot; title=&quot;RSS feed for craigslist | software/QA/DBA/etc jobs &amp;quot; C#&amp;quot; in orlando &quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; cont [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SearchResultsDocument {
            get {
                return ResourceManager.GetString("SearchResultsDocument", resourceCulture);
            }
        }
    }
}
