//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Searcher.SO.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Searcher.SO.Tests.TestData", typeof(TestData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///	&lt;body&gt;
        ///		&lt;div data-jobid=&quot;53709&quot; class=&quot;can-apply&quot;&gt;
        ///                &lt;p class=&quot;posted top&quot;&gt;
        ///                    3 weeks ago
        ///                &lt;/p&gt;
        ///
        ///                &lt;a class=&quot;fav-toggle&quot; data-jobid=&quot;53709&quot; href=&quot;/jobs/togglefavorite/53709?returnUrl=%2Fjobs%3FsearchTerm%3DC%2523%252cASP%252c.NET&quot;&gt;&lt;/a&gt;
        ///                
        ///
        ///                &lt;h3&gt;
        ///                    &lt;a class=&quot;job-link&quot; href=&quot;/jobs/53709/c-sharp-net-developer-mobitrans?a=13vdNxNDy&amp;amp;searchTerm=C%23%2CASP%2C.NET&quot; title=&quot;C# .NET Devel [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JobPostingRow {
            get {
                return ResourceManager.GetString("JobPostingRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;!--[if lt IE 7]&gt;      &lt;html class=&quot;no-js lt-ie9 lt-ie8 lt-ie7&quot;&gt; &lt;![endif]--&gt;
        ///
        ///&lt;!--[if IE 7]&gt;         &lt;html class=&quot;no-js lt-ie9 lt-ie8&quot;&gt; &lt;![endif]--&gt;
        ///&lt;!--[if IE 8]&gt;         &lt;html class=&quot;no-js lt-ie9&quot;&gt; &lt;![endif]--&gt;
        ///&lt;!--[if gt IE 8]&gt;&lt;!--&gt;
        ///&lt;html class=&quot;no-js&quot;&gt;
        ///&lt;!--&lt;![endif]--&gt;
        ///
        ///        &lt;head&gt;
        ///            &lt;title&gt;“C#,ASP,.NET”  Remote Job Listings - Stack Overflow Careers 2.0 &lt;/title&gt;
        ///            &lt;link href=&quot;//cdn-careers.sstatic.net/careers/cso/all.min.css?v=410ea9c5855b&quot; rel=&quot;style [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SearchResultsDocument {
            get {
                return ResourceManager.GetString("SearchResultsDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://careers.stackoverflow.com.
        /// </summary>
        internal static string SearchUrls {
            get {
                return ResourceManager.GetString("SearchUrls", resourceCulture);
            }
        }
    }
}
