//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Searcher.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SearcherEntities : DbContext
    {
        public SearcherEntities()
            : base("name=SearcherEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SearchResultData> SearchResultDatas { get; set; }
        public virtual DbSet<Search> Searches { get; set; }
        public virtual DbSet<SearchTerm> SearchTerms { get; set; }
    }
}
